### ISSUE TITLE
Grafana metrics dashboard in progress request count is negative

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/module-ballerinax-prometheus#111]
**Description:**
I recently tried out metrics monitoring with prometheus and grafana as [mentioned ballerina website](https://ballerina.io/learn/observing-ballerina-programs/observing-your-application-with-prometheus-grafana-and-jaeger/#monitoring-metrics). When I import and view the grafana dashboard, `In progress request` count was always `negative` and the negative value kept on increasing as I send more requests to the underlying ballerina service.

![Screenshot from 2021-12-08 10-14-23](https://user-images.githubusercontent.com/11285165/145149873-c6f46b8a-bdbc-405b-ae6f-a8492da65b71.png)

This needs to be fixed soon since this is the most visible metric in the grafana dashboard.

**Affected Product Version:**
SL Beta 4

**Steps to reproduce:**
See description

**Comment by nadundesilva** [comment]
This issue is specific to the `ballerina/http` module itself.

### Background
We have a method called `stopObservationWithContext` which allows `ballerina/http` module to stop an observation manually (without relying on the compiler instrumentation). This was done to allow support to record the status code and then close the observation manually after a resource method had ended when the user wants to use a `return` instead of `caller-respond()` call.

### Cause
The `ObserveUtils.stopObservationWithContext` method provided for manually stopping an observation is being called twice. This causes the observability to receive one start observation (in progress requests count + 1) call and two stop observation calls (in progress requests count - 2). This results in the in progress decrement by `1` for each http resource call.

### Possible Actions
* Investigate in `ballerina/http` module to figure out why this is being called twice.
* Add a guard from `ObserveUtils.stopObservationWithContext` method to prevent closing an observation twice.
