### ISSUE TITLE
Update Grafana Dashboard to SLP8 metrics

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/module-ballerinax-prometheus#4]
**Description:**
While updating the Observability implementation for Ballerina SLP8, we have made several changes to the generated metrics. However, Grafana dashboard had not yet been updated to reflect these changes. This needs to be updated.

Dashboard: https://github.com/ballerina-platform/module-ballerinax-prometheus/blob/main/grafana-dashboard.json

**Affected Product Version:**
Ballerina SLP8

**Comment by tharinduwijewardane** [comment]
Migrated the dashboard to SwanLake alpha1. 
Sql error graphs are not demonstrated with screenshots, since it is not possible to capture sql errors with ballerina observability at the moment.
The mysql client [returns a stream](http://dev.ballerina.io/swan-lake/learn/by-example/mysql-query-operation.html) and the errors can be thrown when we iterate it, and those are not captured.
